import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Link from 'next/link'
import Providers from '@/components/Providers'
import SignButton from '@/components/SignButton'

// const inter = Inter({ subsets: ["latin"] });

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					fontSans.variable
				)}
			>
				<Providers>
					<header>
						<nav className='flex gap-2 items-center'>
							<Link href='/'>Home</Link>
							<Link href='/dashboard'>Dashboard</Link>
							<SignButton />
						</nav>
					</header>
					{children}
				</Providers>
			</body>
		</html>
	)
}
